apiVersion: v1
kind: Service
metadata:
  name: fakesmtp-web
  labels:
    {{- include "fake-smtp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5080
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "fake-smtp.selectorLabels" . | nindent 4 }}
