apiVersion: v1
kind: Service
metadata:
  name: fakesmtp-smtp
  labels:
    {{- include "fake-smtp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5025
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "fake-smtp.selectorLabels" . | nindent 4 }}
