replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: alpine

containerPort: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: cn.thinktecture-demos.com
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: cn-sample-ingress-cert
     hosts:
     - cn.thinktecture-demos.com

resources:
  limits:
    cpu: 25m
    memory: 32Mi
  requests:
    cpu: 25m
    memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
