apiVersion: v1
kind: Service
metadata:
  name: {{ include "price-watcher.fullname" . }}
  labels:
    {{- include "price-watcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-pwatcher
      protocol: TCP
      name: http
  selector:
    {{- include "price-watcher.selectorLabels" . | nindent 4 }}
